### PR TITLE
ci: Clarify what statuses are accepted

### PR DESCRIPTION
**Pull request by maurelian**
The current error message suggests that a PR cannot be merged if it is labelled as in `DRAFT` status, this is true only because DRAFT doesn't match list of accepted statuses, not because the play book can't be in draft.

image

### CODE REVIEW

**Review by blmalone — APPROVED** [review]
lgtm

**Comment by maurelian** [comment]
This is wrong, it only prints the first valid status: 
2024-07-22 at 10 31@2x

**Comment by maurelian** [comment]
Looks like this now: 
2024-07-22 at 11 19@2x

**Review by mds1 — APPROVED** [review]
This could get verbose and make the results hard to read when there are a lot of invalid statuses, but since typically only 1 task is added per PR in practice it should be ok

**Pull request merged**
