### PR TITLE
Add new pre-signed pauses for Sepolia

### PR DESCRIPTION
**Pull request by pauldowman**
**Description**

The Deputy Guardian Module was updated which broke the [previous pre-signed pause transactions](tasks/sep/011-presigned-pause/). 

This generates new presigned pauses for Sepolia.

**Tests**

Simulation will be run by @Ethnical 

**Additional context**

**Metadata**

- See also https://github.com/ethereum-optimism/security-pod/issues/137

### CODE REVIEW

**Comment by Ethnical** [comment]
Nice @pauldowman Thanks!
We need to rename the folder from  `015-presigned-pause` -> `017-presigned-pause` ( I didn't saw that there is already [PR](https://github.com/ethereum-optimism/superchain-ops/pull/300) executed from proof `15` & `16` so we have to choose the `17`).

**Review by Ethnical — CHANGES_REQUESTED** [review]
Nice @pauldowman Thanks!
We need to rename the folder from 015-presigned-pause -> 017-presigned-pause ( I didn't saw that there is already https://github.com/ethereum-optimism/superchain-ops/pull/300 executed from proof 15 & 16 so we have to choose the 17).

**Comment by Ethnical** [comment]
Simulation has been done using the command: 
 
```bash
forge script /Users/ethnical/sec/ethereum-optimism/superchain-ops/tasks/sep/015-presigned-pause/PresignPauseFromJson.s.sol --sig "sign()" --rpc-url https://ethereum-sepolia.publicnode.com --chain-id 11155111 --sender 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --via-ir -vvvvvvvv
```
This modify the superchain config `PAUSE_SLOT` located at `bytes32(uint256(keccak256("superchainConfig.paused")) - 1)`

The state change of the pause can be seen on this tenderly simulation for the storage `bytes32(uint256(keccak256("superchainConfig.paused")) - 1)` value: 
image

Also the forge logs show the simulation the pause happened correctly with the event `pause` emitted successfully!
image

So the PSPs are valid.

**Comment by pauldowman** [comment]
Renamed folder to `017` to fix conflict with other open PRs, and rebased onto latest `main`.

**Review by Ethnical — APPROVED** [review]

**Pull request merged**
